name: RankedByGamers Gatsby Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # cron job that runs at 00:00 UTC on the 1st and 15th of every month
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
      IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'  # Specify the latest stable LTS version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clear Gatsby Cache
        run: npx gatsby clean  # Use npx to run local Gatsby commands

      - name: Lint code
        run: npm run lint

      - name: Build the project
        run: npx gatsby build  # Use npx to run local Gatsby commands

      - name: Run tests
        run: npm test

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        timeout-minutes: 5  # Increase timeout to allow for successful deployments